### PR TITLE
Distinguish between infinite and pseudo-infinite pipelines

### LINKED ISSUE #604: Unexpected behavior when using repeat() with sample()/round_robin()
**Describe the bug:**
Data pipeline output is cut short when using sample() or round_robin() with repeat()

**Describe how to reproduce:**
```
from fairseq2.data import read_sequence, DataPipeline

pipelines = [read_sequence([1,2,3,4]).repeat().and_return(), read_sequence([5,6,7,8]).repeat().and_return()]

pipeline = DataPipeline.sample(pipelines).and_return()

for example in pipeline:
    print(example)
```

**Describe the expected behavior:**
Expected output: e.g. `1, 5, 2, ...`
Actual output: `1`

**Additional Context:**

Caused by the way infinite data sources are handled in sample/round_robin:

https://github.com/facebookresearch/fairseq2/blob/7ece73ca39ded191d3774d33b318383e07d753e1/native/src/fairseq2n/data/sample_data_source.cc#L175-L176

https://github.com/facebookresearch/fairseq2/blob/7ece73ca39ded191d3774d33b318383e07d753e1/native/src/fairseq2n/data/round_robin_data_source.cc#L137-L138

### PR DESCRIPTION
**Pull request by syleshfb**
**What does this PR do? Please describe:**
Distinguishes between actually infinite (e.g. repeat()) and pseudo-infinite (e.g. count, constant) pipelines in order to allow the use of sample(), round_robin(), and zip() with actually infinite pipelines. 
Pipelines are either finite, pseudo-infinite, or infinite.

Fixes #604 

**Does your PR introduce any breaking changes? If yes, please list them:**
No

**Check list:**
- [ ] Was the content of this PR **discussed and approved** via a GitHub issue? (no need for typos or documentation improvements)
- [ ] Did you read the [contributor guideline](https://github.com/facebookresearch/fairseq2/blob/main/CONTRIBUTING.md)?
- [ ] Did you make sure that your **PR does only one thing** instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**?
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you **update the [CHANGELOG](https://github.com/facebookresearch/fairseq2/blob/main/CHANGELOG.md)**? (no need for typos, documentation, or minor internal changes)

### CODE REVIEW

File: native/src/fairseq2n/data/concat_data_source.cc [hunk 1]
```diff
@@ -13,11 +13,11 @@ namespace fairseq2n::detail {
 concat_data_source::concat_data_source(std::vector<data_pipeline> &&pipelines) noexcept
   : pipelines_(std::move(pipelines))
 {
-    is_infinite_ = std::any_of(
-        pipelines_.begin(), pipelines_.end(), [](const data_pipeline &p)
+    finitude_type_ = std::max_element(
```
Comment (cbalioglu) [inline native/src/fairseq2n/data/concat_data_source.cc:16]: Nit: For better readability, I would separate `std::max_element()` and `->get_finitude_type()` statements.

File: native/src/fairseq2n/data/round_robin_data_source.cc [hunk 2]
```diff
@@ -18,11 +18,12 @@ round_robin_data_source::round_robin_data_source(
 {
     buffer_.reserve(pipelines_.size());
 
-    is_infinite_ = std::all_of(
-        pipelines_.begin(), pipelines_.end(), [](const data_pipeline &p)
+    finitude_type_ = pipelines_.empty() ? data_source_finitude_type::finite : std::max_element(
```
Comment (cbalioglu) [inline native/src/fairseq2n/data/round_robin_data_source.cc:21]: Nit: Same as above. I would split this into 2 or 3 separate statements for better readability.

File: native/src/fairseq2n/data/sample_data_source.cc [hunk 3]
```diff
@@ -48,11 +48,11 @@ sample_data_source::sample_data_source(
 
     buffer_.reserve(pipelines_.size());
 
-    is_infinite_ = std::all_of(
-        pipelines_.begin(), pipelines_.end(), [](const data_pipeline &p)
+    finitude_type_ = pipelines_.empty() ? data_source_finitude_type::finite : std::max_element(
```
Comment (cbalioglu) [inline native/src/fairseq2n/data/sample_data_source.cc:51]: Nit: again, same readability advice as above.

File: tests/unit/data/data_pipeline/test_round_robin.py [hunk 4]
```diff
@@ -60,6 +60,38 @@ def test_op_works_when_infinite_pipeline_is_specified(self) -> None:
...
+        pipeline3 = read_sequence([0, 2, 4, 6]).and_return()
+
+        pipeline = DataPipeline.round_robin(
+            [pipeline1, pipeline2, pipeline3]
+        ).and_return()
+
+        for _ in range(2):
+            it = iter(pipeline)
+
+            [next(it) for i in range(15)] == [
```
Comment (cbalioglu) [inline tests/unit/data/data_pipeline/test_round_robin.py:75]: Nit: Can you please have the entire list in a single line and use `#fmt: skip` to instruct black to ignore this line.

File: native/src/fairseq2n/data/bucket_by_length_data_source.cc [hunk 5]
```diff
@@ -151,10 +151,10 @@ bucket_by_length_data_source::reload_position(tape &t, bool strict)
     inner_->reload_position(t, strict);
 }
 
-bool
-bucket_by_length_data_source::is_infinite() const noexcept
+data_source_finitude_type
+bucket_by_length_data_source::get_finitude_type() const noexcept
```
Comment (cbalioglu) [inline native/src/fairseq2n/data/bucket_by_length_data_source.cc:155]: Nit: since this is mainly an accessor function, for brevity, you can omit the `get_` prefix and just say `finitude_type()`.

File: native/src/fairseq2n/data/finitude_type.h [hunk 6]
```diff
@@ -0,0 +1,13 @@
+// Copyright (c) Meta Platforms, Inc. and affiliates.
```
Comment (cbalioglu) [inline native/src/fairseq2n/data/finitude_type.h:1]: I suggest putting this enum in data_source.h. No need to have a separate file just for this enum.

**Review by cbalioglu — COMMENTED** [review]
Neat! And, thanks a lot for including unit tests! Just left a few nit comments. Once you address them, I think it is good to go.

**Review by cbalioglu — APPROVED** [review]
Neat work! Thanks a lot again for your contribution!
